/**
 * Generates, from schema/candidates.schema.json (the single source of truth):
 *   - src/format/generated/validate.js  precompiled Ajv validator (no eval at runtime)
 *   - src/format/generated/types.ts     TypeScript types
 * Run `pnpm gen`; CI fails if the checked-in output drifts.
 */
import Ajv2020 from 'ajv/dist/2020.js'
import standaloneCode from 'ajv/dist/standalone/index.js'
import addFormats from 'ajv-formats'
import { _ } from 'ajv'
import { compile } from 'json-schema-to-typescript'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'

const root = new URL('../', import.meta.url)
const schema = JSON.parse(readFileSync(new URL('schema/candidates.schema.json', root), 'utf8'))
const outDir = new URL('src/format/generated/', root)
mkdirSync(outDir, { recursive: true })

const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  allowUnionTypes: true,
  code: {
    source: true,
    esm: true,
    formats: _`fullFormats`,
  },
})
addFormats(ajv, ['uri', 'date-time'])
// Annotation for json-schema-to-typescript only; no validation meaning.
ajv.addKeyword({ keyword: 'tsType', schemaType: 'string' })
const validate = ajv.compile(schema)
const header = `// @ts-nocheck\n// GENERATED by scripts/gen-schema-code.ts from schema/candidates.schema.json. Do not edit.\n/* eslint-disable */\nimport { fullFormats } from 'ajv-formats/dist/formats.js'\n`
// Ajv's ESM output still require()s its runtime helpers; rewrite them as imports.
// The helpers are CommonJS with `exports.default = fn`. Bundlers disagree on
// what a default import of that is (Node-style gives the exports object,
// Babel-style gives fn), so import the namespace and unwrap either shape.
let code = standaloneCode(ajv, validate)
const helperImports: string[] = []
code = code.replace(
  /const (\w+) = require\("(ajv\/dist\/runtime\/\w+)"\)\.default;/g,
  (_m, name: string, mod: string) => {
    helperImports.push(
      `import * as ${name}_ns from '${mod}.js'\nconst ${name} = typeof ${name}_ns.default === 'function' ? ${name}_ns.default : ${name}_ns.default.default`,
    )
    return ''
  },
)
if (code.includes('require(')) throw new Error('unhandled require() in generated validator')
writeFileSync(new URL('validate.js', outDir), header + helperImports.join('\n') + '\n' + code)

const types = await compile(schema, 'CandidateCollection', {
  bannerComment:
    '// GENERATED by scripts/gen-schema-code.ts from schema/candidates.schema.json. Do not edit.',
  additionalProperties: false,
  unreachableDefinitions: false,
  style: { semi: false, singleQuote: true },
})
writeFileSync(new URL('types.ts', outDir), types)
writeFileSync(
  new URL('validate.d.ts', outDir),
  `// GENERATED by scripts/gen-schema-code.ts. Do not edit.
import type { ErrorObject } from 'ajv'
import type { CandidateCollection } from './types'

export interface ValidateFunction {
  (data: unknown): data is CandidateCollection
  errors?: ErrorObject[] | null
}
export declare const validate: ValidateFunction
export default validate
`,
)
console.log('generated validate.js, validate.d.ts and types.ts')
